/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/layout`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/page`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/registration/AccountSetupScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/registration/AccountSuccessScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/registration/EvacuationCenterScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/registration/EvacuationDetailsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/registration/FinalRemindersScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/registration/HouseholdScanScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/registration/LocationDetailsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/registration/HouseholdInfoScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/two` | `/two`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/layout`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/page`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/registration/AccountSetupScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/registration/AccountSuccessScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/registration/EvacuationCenterScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/registration/EvacuationDetailsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/registration/FinalRemindersScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/registration/HouseholdScanScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/registration/LocationDetailsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/registration/HouseholdInfoScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/two` | `/two`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/layout${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/page${`?${string}` | `#${string}` | ''}` | `/../screens/registration/AccountSetupScreen${`?${string}` | `#${string}` | ''}` | `/../screens/registration/AccountSuccessScreen${`?${string}` | `#${string}` | ''}` | `/../screens/registration/EvacuationCenterScreen${`?${string}` | `#${string}` | ''}` | `/../screens/registration/EvacuationDetailsScreen${`?${string}` | `#${string}` | ''}` | `/../screens/registration/FinalRemindersScreen${`?${string}` | `#${string}` | ''}` | `/../screens/registration/HouseholdScanScreen${`?${string}` | `#${string}` | ''}` | `/../screens/registration/LocationDetailsScreen${`?${string}` | `#${string}` | ''}` | `/../screens/registration/HouseholdInfoScreen${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/two${`?${string}` | `#${string}` | ''}` | `/two${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/layout`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/page`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/registration/AccountSetupScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/registration/AccountSuccessScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/registration/EvacuationCenterScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/registration/EvacuationDetailsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/registration/FinalRemindersScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/registration/HouseholdScanScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/registration/LocationDetailsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/registration/HouseholdInfoScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/two` | `/two`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
